### PR TITLE
Fix furniture: Instead of replace, it was delete, place.

### PR DESCRIPTION
**Pull request by Marmur2020**
Thanks https://github.com/Asleeepp/skript-itemsadder/issues/4

### CODE REVIEW

**Comment by Asleeepp** [comment]
What? This method doesn't exist anywhere in the ItemsAdder API.

**Comment by Marmur2020** [comment]
> What? This method doesn't exist anywhere in the ItemsAdder API.

There is this method, it's just that I didn't notice that the code was misspelled at the time. I compiled the plugin and it works fine and there is no bug that it turns the wrong way.

**Comment by Marmur2020** [comment]
line 133: https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomFurniture.java

**Comment by Marmur2020** [comment]
I forgot to thank you for the wonderful addon, and I'm even interested in developing it)

**Comment by Asleeepp** [comment]
> line 133: https://github.com/LoneDev6/API-ItemsAdder/blob/master/src/main/java/dev/lone/itemsadder/api/CustomFurniture.java

whattttt?? this is no where in the javadocs, i've been scammed

**Pull request merged**
