### PR TITLE
Create EffReplaceCustomFurniture.java

### PR DESCRIPTION
**Pull request by Marmur2020**
Replaces existing furniture with new furniture
Example: replace custom furniture "ia:my_furniture" at location of player's target block 

https://github.com/Asleeepp/skript-itemsadder/assets/109208530/a8503abf-b632-4815-ae51-3f42d184d582

### CODE REVIEW

**Comment by Marmur2020** [comment]
I think you'll like it.)

**Comment by Asleeepp** [comment]
I like the idea, but I think I'd rather just have a specific "remove custom furniture" effect, rather then a "replace" one.
I'll work on it for the next update.

**Comment by Marmur2020** [comment]
> I like the idea, but I think I'd rather just have a specific "remove custom furniture" effect, rather then a "replace" one. I'll work on it for the next update.

I don't know, for me this feature made it easier to implement the mechanics of washing gravel to get useful items for stoneblock. That way I had to replace the model with another one. Honestly I wouldn't remove the mechanics and replace with a remove and add method. I may not know what you want to do.

**Comment by Asleeepp** [comment]
> I don't know, for me this feature made it easier to implement the mechanics of washing gravel to get useful items for stoneblock. That way I had to replace the model with another one. Honestly I wouldn't remove the mechanics and replace with a remove and add method. I may not know what you want to do.

mmm, I'll add it alongside a remove effect, then.

**Review by Asleeepp — APPROVED** [review]

**Pull request merged**
